/**
 * FDTD Simulation Data Loaders
 *
 * TypeScript loaders for FDTD simulation export files generated by
 * the Python `metamaterial.io` module.
 *
 * @example
 * ```typescript
 * import {
 *   loadManifest,
 *   loadMetadata,
 *   loadSnapshot,
 *   loadGeometry,
 *   loadProbeData,
 * } from '@/lib/loaders';
 *
 * // Load simulation manifest
 * const manifest = await loadManifest('/data/helmholtz_manifest.json');
 *
 * // Load metadata for grid info
 * const metadata = await loadMetadata(manifest.metadata);
 * console.log(`Grid: ${metadata.grid.shape.join('x')}`);
 *
 * // Load first snapshot with progress
 * const snapshot = await loadSnapshot(
 *   manifest.snapshots[0].file,
 *   manifest.snapshots[0],
 *   { onProgress: (loaded, total) => console.log(`${loaded}/${total}`) }
 * );
 *
 * // Load geometry for solid boundaries
 * const geometry = await loadGeometry(manifest.geometry, {
 *   shape: metadata.grid.shape,
 *   format: 'packed_bits',
 *   file: manifest.geometry,
 * });
 *
 * // Load probe time series
 * const probes = await loadProbeData(manifest.probes);
 * ```
 *
 * @module loaders
 */

// Type exports
export type {
  // Core data types
  Snapshot,
  VelocitySnapshot,
  Geometry,
  ProbeData,
  // Metadata types
  SnapshotInfo,
  VelocitySnapshotInfo,
  GeometryInfo,
  SimulationManifest,
  SimulationMetadata,
  // Format types
  RLEGeometry,
  // Options
  LoadOptions,
} from './types';

// Manifest/metadata loaders
export { loadManifest, loadMetadata } from './manifest';

// Snapshot loader
export { loadSnapshot, loadSnapshots, loadVelocitySnapshot } from './snapshot';

// Geometry loader
export { loadGeometry } from './geometry';

// Probe data loader
export {
  loadProbeData,
  getTimeArray,
  getFrequencyResponse,
  findPeakFrequency,
} from './probes';

// HDF5 loader
export {
  loadHDF5File,
  loadHDF5FromBuffer,
  loadHDF5FromURL,
  loadTimestep,
  toSimulationMetadata,
  type HDF5SimulationData,
  type HDF5Metadata,
  type HDF5Grid,
  type HDF5SimulationParams,
  type HDF5Source,
  type HDF5LoadOptions,
  type HDF5URLLoadResult,
} from './hdf5';

// =============================================================================
// Convenience Functions
// =============================================================================

import { loadManifest, loadMetadata } from './manifest';
import { loadSnapshots } from './snapshot';
import { loadGeometry } from './geometry';
import { loadProbeData } from './probes';
import type {
  SimulationManifest,
  SimulationMetadata,
  Snapshot,
  Geometry,
  ProbeData,
  LoadOptions,
} from './types';

/**
 * Complete simulation data loaded from export.
 */
export interface SimulationData {
  manifest: SimulationManifest;
  metadata: SimulationMetadata;
  geometry: Geometry;
  probes: ProbeData;
  snapshots: Snapshot[];
}

/**
 * Load complete simulation from manifest.
 *
 * This convenience function loads all simulation data in one call.
 * For large simulations with many snapshots, prefer loading snapshots
 * individually or in batches.
 *
 * @param manifestUrl - URL to manifest JSON file
 * @param options - Loading options
 * @returns Complete simulation data
 *
 * @example
 * ```typescript
 * const sim = await loadSimulation('/data/helmholtz_manifest.json', {
 *   onProgress: (loaded, total) => {
 *     progressBar.value = loaded / total;
 *   }
 * });
 *
 * console.log(`Loaded ${sim.snapshots.length} snapshots`);
 * console.log(`Grid: ${sim.metadata.grid.shape.join('x')}`);
 * ```
 */
export async function loadSimulation(
  manifestUrl: string,
  options: LoadOptions = {}
): Promise<SimulationData> {
  // Load manifest first
  const manifest = await loadManifest(manifestUrl, options);

  // Resolve relative paths from manifest URL
  const baseUrl = manifestUrl.substring(0, manifestUrl.lastIndexOf('/') + 1);
  const resolvePath = (path: string) => {
    if (path.startsWith('/') || path.startsWith('http')) {
      return path;
    }
    // Extract just the filename from the path
    const filename = path.split('/').pop() || path;
    return baseUrl + filename;
  };

  // Load metadata first (needed for geometry shape)
  const metadata = await loadMetadata(resolvePath(manifest.metadata), options);

  // Load geometry and probes in parallel (now that we have the shape)
  const [geometry, probes] = await Promise.all([
    loadGeometry(resolvePath(manifest.geometry), {
      shape: metadata.grid.shape,
      format: 'packed_bits',
      file: manifest.geometry,
    }, options),
    loadProbeData(resolvePath(manifest.probes), options),
  ]);

  // Load all snapshots
  const snapshotPairs: Array<[string, typeof manifest.snapshots[0]]> =
    manifest.snapshots.map((info) => [resolvePath(info.file), info]);

  const snapshots = await loadSnapshots(snapshotPairs, options);

  return {
    manifest,
    metadata,
    geometry,
    probes,
    snapshots,
  };
}
